"""The 0.7 disposable-unit fixture shared by the installed Python gates.

The generated unit is kept as setup prints it; only the installation paths,
unit-owned directory names and listed flags change. The database is made the
way setup makes it (agent-busd -init as the daemon account), because the unit
never creates one. Nothing here names or opens the live installation.
"""
import json
import re
from pathlib import Path
import subprocess as sp

LIVE_STATE = "/var/lib/agent-bus/daemon"
LIVE_LOGS = "/var/log/agent-bus"
LIVE_RUNTIME = "/run/agent-bus"


def run(*args, **kw):
    return sp.check_output(list(map(str, args)), text=True, **kw)


def root(*args, **kw):
    return run("sudo", "-n", *args, **kw)


class Fixture:
    def __init__(self, name):
        self.name = name
        self.state = Path("/var/lib") / name
        self.runtime = Path("/run") / name
        self.logs = Path("/var/log") / name
        self.db = self.state / "agent-bus.db"
        self.unit_path = Path("/run/systemd/system") / (name + ".service")

    def unit(self, setup, busd, owner, flags="", keep=lambda line: True):
        text = run(setup, "--print-unit", "--owner", owner, "--addr", "127.0.0.1:0", "--exec", busd)
        for live in (LIVE_STATE, LIVE_LOGS, LIVE_RUNTIME):
            if live not in text:
                raise RuntimeError(f"generated unit no longer names {live}; the fixture would touch it")
        text = text.replace("StateDirectory=agent-bus/daemon", f"StateDirectory={self.name}")
        text = text.replace("RuntimeDirectory=agent-bus\n", f"RuntimeDirectory={self.name}\n")
        text = text.replace(LIVE_STATE, str(self.state)).replace(LIVE_LOGS, str(self.logs))
        text = text.replace(LIVE_RUNTIME, str(self.runtime))
        lines = []
        for line in text.splitlines():
            if line.startswith("ExecStart=") and flags:
                line += " " + flags
            if keep(line):
                lines.append(line)
        text = "\n".join(lines) + "\n"
        for live in (LIVE_STATE, LIVE_LOGS, LIVE_RUNTIME):
            if re.search(re.escape(live) + r"(?![\w.-])", text):
                raise RuntimeError(f"disposable unit still names {live}")
        return text

    def prepare(self, busd, owner, mount=None):
        """State and log directories as setup leaves them, then -init.
        mount, when given, is tmpfs options for a bounded state filesystem."""
        root("mkdir", "-m", "0700", "-p", self.state)
        if mount:
            root("mount", "-t", "tmpfs", "-o", mount, self.name, self.state)
        root("chown", "agent-busd:agent-busd", self.state)
        root("chmod", "0700", self.state)
        root("mkdir", "-m", "0750", "-p", self.logs)
        root("chown", "agent-busd:agent-busd", self.logs)
        root("runuser", "-u", "agent-busd", "--", busd, "-owner", owner, "-db", self.db, "-init")

    def install(self, text, out, label="unit.service"):
        (out / label).write_text(text)
        root("cp", out / label, self.unit_path)
        root("systemctl", "daemon-reload")

    def owner_token(self, owner):
        """The daemon account's own socket is the owner's; the credential
        lives in the database, so it is asked for rather than read."""
        answer = root("runuser", "-u", "agent-busd", "--", "curl", "--silent", "--fail",
                      "--max-time", "4", "--unix-socket", self.runtime / "user-agent-busd.sock",
                      "--header", "Content-Type: application/json",
                      "--data-binary", json.dumps({"name": owner}), "http://bus/token")
        return json.loads(answer)["token"]

    def journal(self):
        return root("journalctl", "--no-pager", "-u", self.name)

    def remove(self):
        sp.run(["sudo", "-n", "systemctl", "stop", self.name])
        root("rm", "-f", self.unit_path)
        root("systemctl", "daemon-reload")
        sp.run(["sudo", "-n", "umount", self.state], stderr=sp.DEVNULL)
        # The names are generated by the gate, never taken from input.
        root("rm", "-rf", self.state, self.runtime, self.logs)
